### ISSUE TITLE
Add new PackageSettings

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit.portable.agent#10]
Need to add `TestParameters` and remove engine settings.

**Comment by CharliePoole** [comment]
To match what's happening in the engine, you may want a FrameworkSettings.cs file instead. The engine will use that plus EngineSettings.cs based on the discussion with @ChrisMaddock

**Comment by rprouse** [comment]
Thanks, I have removed the engine settings from the current implementation, so renaming it to `FrameworkSettings` makes sense.
