### ISSUE TITLE
Add ability to run multiple assemblies

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit.portable.agent#13]
Agent should manage running multiple assemblies and combining the results, to avoid this functionality being duplicated in each runner.

**Comment by ChrisMaddock** [comment]
@rprouse - I haven't worked with this bit of NUnit before, could I get some feedback in terms of architecture?

In terms of storing the tests, I was going for a mini 'TestPackage', which would just store a framework/test assembly/framework controller. That would be created on `Load()`, and all the other public methods in `NUnitPortableDriver` would just iterate through each test package and combine the results. (Keeping this single-threaded for now, I feel like default parallelization would also need to come with option to turn parallelization _off_ - which feels like phase 2!)

Combining the results seems more difficult, it looks like I'll basically have to duplicate `ResultHelper` from the engine. Am I missing anything here?

Thanks

**Comment by rprouse** [comment]
@ChrisMaddock I will need to dive back into the code to help you on this. I haven't touched it in so long I've lost my mind-map of the architecture, sorry.

**Comment by rprouse** [comment]
I have been copying from the engine though. Generally it is pretty straight forward except for the change to LINQ to XML.

**Comment by ChrisMaddock** [comment]
@rprouse - Actually, disregard the above! I spotted the `ResultSummary` class being used in `dotnet-test-nunit`, which was the missing link I was looking for!

Aiming to get a WIP PR sorted soon.
